AllCops:
  TargetRubyVersion: 2.4

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Style/StringLiterals:
  EnforcedStyle: single_quotes

Naming/AccessorMethodName:
  Enabled: false

Metrics/LineLength:
  Max: 100
Documentation:
  Enabled: true

MethodLength:
  Max: 12

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
